remove noarch: python
conda-forge/nose-feedstock pull request #24
Opened 2020-10-09 20:54 UTC by dwhswenson

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [N/A] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)  (done 24 hours ago)
* [N/A] Ensured the license file is being packaged. (assume the package author did)

Fixes #23.

Wheels for Python 2/3 contained different source code, so the single (Python 3) tarball doesn't work for Python 2.

2020-10-09 20:54 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-09 21:07 UTC, beckermr requested changes
This PR should add a constraint on python.

2020-10-09 21:10 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2020-10-09 21:11 UTC, beckermr commented on recipe/meta.yaml
>    entry_points:
```suggestion
  noarch: python
  entry_points:
```

2020-10-09 21:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-10-09 21:12 UTC, beckermr commented
@conda-forge-admin rerender

2020-10-09 21:16 UTC, beckermr commented
@conda-forge-admin rerender

2020-10-09 21:51 UTC, jakirkham commented
> This PR should add a constraint on python.

I'm not sure. It uses 2to3, which we typically don't make `noarch`. Admittedly we don't care about building the Python 2 part any more. Though I'm not sure how 2to3 behaves on different Python 3 versions. Since it is part of Python, it is possible that the 2to3 code changes in noticeable ways between Python minor versions.

2020-10-09 22:31 UTC, beckermr commented
cc @mariusvniekerk any thoughts here?

2020-10-11 15:34 UTC, isuruf approved these changes

2020-10-11 16:01 UTC, beckermr approved these changes

2020-10-11 16:01 UTC, beckermr commented
@conda-forge/nose ready to merge!

2020-10-11 16:48 UTC, merged

2020-10-11 20:16 UTC, moorepants commented
I ask, because I'm not getting build errors in a downstream package that tests against Python 2.7 still using nose. I'm guessing that a Python 3 only compatible version is being installed in my Python 2 conda environment.

2020-10-11 20:29 UTC, jakirkham commented
Please see issue ( https://github.com/conda-forge/nose-feedstock/issues/23 )

2020-10-12 05:19 UTC, moorepants commented
That's the same error I'm now getting in my builds. So if I need nose in a Py 2.7 environment, how do I get that? I can't say `nose<1.3.7` because the version hasn't changed in 5 years. Is there a prior build number that works with p27? Can I use that somehow?

2020-10-12 05:42 UTC, jakirkham commented
Can you please file a new issue sharing what is being run and what the output is? We made a number of changes in the past few days and it's not clear how this issue is being run into since those changes.

2020-10-12 05:50 UTC, moorepants commented
Sure. Thanks.

2020-10-12 05:52 UTC, moorepants commented
I just reran my CI build where I was getting the failure and no longer do, so maybe I was pulling in nose prior to these new changes before. If anything else comes up I'll make an issue. Good for now.

2020-10-12 06:43 UTC, jakirkham commented
Thanks for the update. Glad things are working again 🙂